spark.master                     spark://spark-master:7077
spark.app.name                   bronze-youtube-comments
spark.sql.shuffle.partitions     4
spark.streaming.stopGracefullyOnShutdown true
spark.jars.ivy                   /tmp/.ivy2
spark.local.dir                  /tmp/spark-local
spark.cores.max                  2
spark.executor.cores             1
spark.executor.memory            512m
spark.sql.catalogImplementation  hive
spark.hadoop.hive.metastore.uris thrift://hive-metastore:9083
spark.sql.warehouse.dir          hdfs://namenode:8020/user/hive/warehouse
